lappend define(installed_flow)       lib_index
proc gdraw_lib_index {} {
  set kout [open .godel/ghtm.tcl w]
  puts $kout "set flow_name lib_index"
  puts $kout "ghtm_top_bar"
  puts $kout ""
  puts $kout "if !\[file exist timing.lib\] {"
  puts $kout "  puts \"Error: timing.lib not exist...\""
  puts $kout "  return"
  puts $kout "}"
  puts $kout ""
  puts $kout "package require lip"
  puts $kout ""
  puts $kout "set glib \[read_lib timing.lib\]"
  puts $kout ""
  puts $kout "# cell"
  puts $kout "foreach gcell \[get_subgroups \$glib\] {"
  puts $kout "    set cell_name \[get_group_name \$gcell\]"
  puts $kout "    set name \[get_group_name \$gcell\]"
  puts $kout "    set type \[get_group_type \$gcell\]"
  puts $kout "    #puts \"    \$type\(\$name\)\""
  puts $kout "  #list_attributes \$gcell {    }"
  puts $kout "  # pin"
  puts $kout "  foreach gpin \[get_subgroups \$gcell\] {"
  puts $kout "    set pin_name \[get_group_name \$gpin\]"
  puts $kout "    set name \[get_group_name \$gpin\]"
  puts $kout "    set type \[get_group_type \$gpin\]"
  puts $kout "    set break_pin 0"
  puts $kout "    #puts \"      \$type\(\$name\)\""
  puts $kout "    #list_attributes \$gpin {        }"
  puts $kout "      # timing"
  puts $kout "      foreach g3 \[get_subgroups \$gpin\] {"
  puts $kout "        set name \[get_group_name \$g3\]"
  puts $kout "        set type \[get_group_type \$g3\]"
  puts $kout "        set g3_type \[get_group_type \$g3\]"
  puts $kout "        set break_g3 0"
  puts $kout "        #puts \"3        \$type\(\$name\)\""
  puts $kout "        #list_attributes \$g3 {            }"
  puts $kout "         # rise/fall"
  puts $kout "          foreach g4 \[get_subgroups \$g3\] {"
  puts $kout "            set name \[get_group_name \$g4\]"
  puts $kout "            set type \[get_group_type \$g4\]"
  puts $kout "            set g4_type \[get_group_type \$g4\]"
  puts $kout "            if {\$g3_type == \"timing\" && \$g4_type == \"cell_rise\"} {"
  puts $kout "              #puts \"4            \$type\(\$name\)\""
  puts $kout "              #list_attributes \$g4 {                }"
  puts $kout "              set index1 \[get_attribute_value \$g4 index_1\]"
  puts $kout "              set index2 \[get_attribute_value \$g4 index_2\]"
  puts $kout "              set values \[get_attribute_value \$g4 values\]"
  puts $kout "              puts \"\$cell_name: \$pin_name: \$g4_type :  tran: \$index1\""
  puts $kout "              puts \"\$cell_name: \$pin_name: \$g4_type :  load: \$index2\""
  puts $kout "              #puts \"\$cell_name: \$pin_name: \$g4_type : delay: \$values\""
  puts $kout "              #puts \$index1"
  puts $kout "              set break_g3   1"
  puts $kout "              set break_pin  1"
  puts $kout "              break;"
  puts $kout "            }"
  puts $kout "          }"
  puts $kout "        if {\$break_g3} { break; }"
  puts $kout "        #puts \"in g3\""
  puts $kout "      }"
  puts $kout "      if {\$break_pin} { break; }"
  puts $kout "      #puts \"in pin\""
  puts $kout "  }"
  puts $kout "  #puts \"in cell\""
  puts $kout "}"


  close $kout
}
