lappend define(installed_flow) chklist
proc gdraw_chklist {} {
  upvar env env
  if ![file exist .chklist.js] {
    file copy $env(GODEL_ROOT)/scripts/js/chklist.js .chklist.js
  }
  set kout [open .godel/ghtm.tcl w]
    puts $kout "set flow_name chklist"
    if {$env(GODEL_DEV_MODE)} {
      puts $kout "ghtm_top_bar"
    }

    puts $kout "cd chklist"
    puts $kout "set typelist \[glob *]"
    puts $kout "cd .."
    puts $kout "foreach type \[list Pass Fail Waived] {"
    puts $kout "  foreach i \[array names vars *,\$type] {"
    puts $kout "    set vars(\$i) 0"
    puts $kout "  }"
    puts $kout "}"
    puts $kout ""
    puts $kout "foreach i \[glob chklist/*/*/clvars.tcl] {"
    puts $kout "  source \$i"
    puts $kout "}"
    puts $kout "#parray clvars"
    puts $kout "foreach type \$typelist {"
    puts $kout "  foreach i \[array names clvars \$type*,status] {"
    puts $kout "    set status \$clvars(\$i)"
    puts $kout "    if {\$status == \"pass\"} {"
    puts $kout "      incr vars(\$type,Pass)"
    puts $kout "    } elseif {\$status == \"fail\"} {"
    puts $kout "      incr vars(\$type,Fail)"
    puts $kout "    } else {"
    puts $kout "      incr vars(\$type,Waived)"
    puts $kout "    }"
    puts $kout "  }"
    puts $kout "}"
    puts $kout ""
    puts $kout "set typelist \$typelist"
    puts $kout "tbl_set_cols chk_summary {Pass Fail Waived}"
    puts $kout "tbl_set_rows chk_summary \$typelist"
    puts $kout "ghtm_table_nodir chk_summary 2"
    puts $kout ""
    puts $kout "foreach i \[array names clvars *,owner] {"
    puts $kout "  set chkname \[lindex \[split \$i ,] 0]"
    puts $kout "  set status \$clvars(\$chkname,status)"
    puts $kout "  if {\$clvars(\$i) == \"\"} {"
    puts $kout "    lappend ownerlist Nobody"
    puts $kout "    if {\$status == \"pass\"} {"
    puts $kout "      incr vars(Nobody,Pass)"
    puts $kout "    } elseif {\$status == \"fail\"} {"
    puts $kout "      incr vars(Nobody,Fail)"
    puts $kout "    } else {"
    puts $kout "      incr vars(Nobody,Waived)"
    puts $kout "    }"
    puts $kout "  } else {"
    puts $kout "    set owner \$clvars(\$i)"
    puts $kout "    lappend ownerlist \$owner"
    puts $kout "    if {\$status == \"pass\"} {"
    puts $kout "      incr vars(\$owner,Pass)"
    puts $kout "    } elseif {\$status == \"fail\"} {"
    puts $kout "      incr vars(\$owner,Fail)"
    puts $kout "    } else {"
    puts $kout "      incr vars(\$owner,Waived)"
    puts $kout "    }"
    puts $kout "  }"
    puts $kout "}"
    puts $kout "set ownerlist \[lsort -unique \$ownerlist]"
    puts $kout "#parray clvars *,owner"
    puts $kout "tbl_set_cols     owner {Pass Fail Waived}"
    puts $kout "tbl_set_rows     owner \$ownerlist"
    puts $kout "ghtm_table_nodir owner 2"

    puts $kout ""
    puts $kout "#ghtm_paragraph p1"
    puts $kout "chklist_table"
    puts $kout ""
    puts $kout "puts \$fout \"<button onclick=\\\"chklist_examine()\\\">Commit Changes</button>\""
    puts $kout "puts \$fout \"<br>\""
    puts $kout "puts \$fout \"<textarea id=\\\"text_board\\\" style=\\\"display:none\\\"></textarea>\""
    puts $kout ""
    puts $kout "puts \$fout \"<script src=.chklist.js></script>\""

  close $kout
}
