f:
	@find -type f ! -regex ".*gtcl\|.*tcl\|.*htm\|.*flist\|.*Makefile.*\|.*js\|.*css" > flist
#f:
#	@find -type f -regex ".*pptx\|.*pdf\|.*docx\|.*wmv\|.*tar.gz\|.*zip\|.*svg\|.*mp4\|.*msg" > flist

clean:
	@rm -f /mnt/c/Users/chihkang/Downloads/ginst.tcl
	@rm -f /mnt/c/Users/chihkang/Downloads/gtcl.tcl
