f:
	@find -type f ! -regex ".*gtcl\|.*tcl\|.*htm\|.*flist\|.*Makefile.*\|.*js\|.*css\|.*swp" > flist

f1:
	@find -maxdepth 1 -type f ! -regex ".*gtcl\|.*tcl\|.*htm\|.*flist\|.*Makefile.*\|.*js\|.*css\|.*swp" > flist

clean:
	@rm -f /mnt/c/Users/chihkang/Downloads/ginst.tcl
	@rm -f /mnt/c/Users/chihkang/Downloads/gtcl.tcl
