# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

#@> Shell Options
set -o notify
set -o ignoreeof
shopt -s histappend
shopt -s cdspell

#@> Completion options

#@> History Options
# Don't put duplicate lines in the history.
 export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
# Ignore some controlling instructions
 export HISTIGNORE=$'[ \t]*:&:[fb]g:exit'
 export HISTIGNORE=$'[ \t]*:&:[fb]g:exit:ls' # Ignore the ls command as well
 export PROMPT_COMMAND="history -a"

 export DISPLAY=:0.0
 export LANG=C.UTF-8
 export LC_CTYPE=C.UTF-8
 export PATH=.:$HOME/bin:$HOME/bin/lip:$PATH
 export TCLLIBPATH="/lib /home/USER/usr/local/lib /home/USER/usr/lib"

#@> Bind Key
 bind '"\C-o":"cd ..\C-m"'

#@> Aliases
 if [ -f "${HOME}/.bash_aliases" ]; then
   source "${HOME}/.bash_aliases"
   #source /cygdrive/c/Users/USER/.bash_aliases
 fi

 alias q='exit'
 alias h='history'
 alias note='vi ~/.note'
 alias rmf='rm -rf'
 alias df='df -h'
 alias du='du -h'
# alias less='less -r'                          # raw control characters
# alias whence='type -a'                        # where, of a sort
 alias grep='grep --color'                     # show differences in colour
 alias egrep='egrep --color=auto'              # show differences in colour
 alias fgrep='fgrep --color=auto'              # show differences in colour
 alias ls='ls -hF --color=tty'                 # classify files in colour
 alias la='ls -hltr'
 alias so='source'
 alias m='more'
 alias sm='more Makefile'
 alias sc='source ~/.bashrc'

 vi () {
   /cygdrive/c/Program\ Files\ \(x86\)/Vim/vim81/gvim.exe `cygpath -w $@` &
 }

 alias virc='vi ~/.bashrc'

 cdls () {
   cd $1 && ls;
 }
 alias cd='cdls'
