h:
	@gget . h
1:
	gen_tclvim.tcl

i1:
	cp -f tcl.vim ~/.vim/syntax/tcl.vim
i2:
	cp -f tcl.vim ~/vimfiles/syntax/tcl.vim
i3:
	cp -f tcl.vim ${VIM}/syntax/tcl.vim

renew:
	mv new.cmd.list    cmd.list
	mv new.string.list string.list

clean:
	rm -rf tcl.vim new.cmd.list new.string.list
