#!/bin/csh -f
setenv LC_CTYPE zh_TW.UTF-8
setenv LANG zh_TW.UTF-8
#setenv PROJ_NAME none
#setenv PROJ_ROOT `pwd`
#set prompt="%{\033[1;33m%}[$PROJ_NAME]:[%c4]%%%{\033[0m%} "
set prompt=" \
%{\033[1;33m%}[%~] \
%%%{\033[0m%} "
setenv MANPATH /usr/share/man:/usr/man:/usr/local/share/man:/usr/local/man:/usr/X11R6/man
setenv MANPATH $HOME/usr/local/man:$MANPATH

setenv LD_LIBRARY_PATH $HOME/usr/lib:/usr/local/lib:/usr/lib:$HOME/usr/local/lib

setenv EDITOR /usr/bin/vim
setenv PAGER less
# Set directory color(di) to pink. Ref: dircolors
setenv LS_COLORS "di=01;35:or=40;31;01:*.tdef=01;31:*.gz=01;31:*.rar=01;31:*.tcl=01;1" ;# Light blue background
setenv LM_LICENSE_FILE
setenv NO_AT_BRIDGE 1

set path = (\
   . \
   ~/bin \
   ~/usr/bin \
   ~/usr/local/bin \
   /bin \
   /usr/bin \
   /usr/local/bin \
)
setenv PATH ${PATH}:/usr/X11R6/bin

# Where my perl module installed
setenv PERL5LIB    $HOME/usr/perllib/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi:$HOME/usr/perllib/lib/perl5/site_perl/5.8.8:$HOME/usr/perllib
# Where my tcl package installed
setenv TCLLIBPATH  "/lib $HOME/usr/local/lib $HOME/usr/lib"
#-----------------------------------------------
# Tcsh setting
#-----------------------------------------------
set   history = 1000
set   savehist = 1000
unset ignoreeof
set   autoexpand
set   autolist          # List possible completion choice when tab
set   color             # Color the autolist

umask 002

set   nobeep
limit coredumpsize 0
limit stacksize unlimited
unset prompt3           # disable the harassing auto correct message
unset correct

bindkey -e
# Bind Ctrl-o to `cd ..\n'
bindkey -s "^o" "cd ..\n"
bindkey "^w" backward-delete-word

#-----------------------------------------------
# Alias
#-----------------------------------------------
unalias rm
alias jp 'cd $PROJ_ROOT'
alias pj 'eval `eval pj.pl`;jp'
alias vi 'gvim -f \!* &'
#alias ls 'ls --hide=CVS --color=auto'
alias ls 'ls --color=auto'
alias sc "source $HOME/.cshrc"
alias myprocess 'ps -ef | grep $USER'
#alias setprompt 'set prompt="%{\033[1;33m%}[$PROJ_NAME]:[%c3]%%%{\033[0m%} "'  
alias setprompt 'set prompt=" \\
%{\033[1;33m%}[%~] \\
%%%{\033[0m%} "'  

alias cd 'cd \!*;setprompt;ls'
alias la 'ls -hltr'
alias ll 'ls -la'
alias lx 'ls -l -X'
alias lh 'ls -sLh'
alias lk '\ls --color'
alias df 'df -H'
alias du 'du -sh'
alias q exit
alias h  'history'
alias igp 'gp \!* | xclip'
# icl: intelligent xclip. 
alias icl '\!* | xclip'
alias m more
alias sm 'more Makefile'
alias so 'source'
alias dirdu 'find ./ -maxdepth 1 -mindepth 1 -type d | xargs du -s --si'
alias goe 'chmod +x \!*'
alias note 'vi $HOME/.note'
alias my-path 'echo $path\\
            | sed "y/ /\n/\\
                   s/\(\n\)/\1     /g\\
                   s/^/path = /"'
alias cvsupdate 'cvs -q update -d'
alias cvschk    'cvs -n -q update -d | grep -v FE'
alias cvsci     'cvs ci -m "" \!*'
alias so-alias  'source ~/.alias'
alias ff 'find ./ -name "\!*"'
alias make-cmds 'grep "^[^#[:space:]].*:" Makefile '
alias hcd 'eval `gen-hcd-path.csh \!*`'

alias gitdiff 'git difftool \!*`'
alias rmf 'rm -rf'

if (-e $HOME/.alias) then
  source $HOME/.alias
endif

# vim:fdm=marker
